name: CI

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev
  
# dummy (unit)
env: 
  NODE_ENV: test
  PORT: 3000
  DATABASE_URL: "postgresql://dummy:dummy@localhost:5432/dummy"
  FRONT_URL: "http://localhost:3000"
  BETTER_AUTH_SECRET: "dummy_secret_for_test"
  BETTER_AUTH_URL: "http://localhost:3000"

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm exec prisma generate

      - name: Build
        run: pnpm build

      - name: Run Tests
        run: pnpm test
